spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mercadolivro?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ajudazupper
  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone

jwt:
  secret: ceae87e0-d16b-4a32-ae69-008b4b8a0629
  expiration: 999999